// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package model

// Location defines model for Location.
type Location struct {
	Lat *float32 `json:"lat,omitempty"`
	Lng *float32 `json:"lng,omitempty"`
}

// OrderHistory defines model for OrderHistory.
type OrderHistory struct {
	History *[]Location `json:"history,omitempty"`
	OrderId *string     `json:"order_id,omitempty"`
}

// GetHistoryParams defines parameters for GetHistory.
type GetHistoryParams struct {

	// Maximum number of history item
	Max *int `json:"max,omitempty"`
}
