openapi: 3.0.1
info:
  title: Location History
  description: In-memory location history server
  contact:
    email: iboware@gmail.com
  version: "1.0"
servers:
- url: http://order.example.com/v1
tags:
- name: location
  description: Order Location
paths:
  /location/{order_id}:
    get:
      tags:
      - location
      summary: Returns order history
      description: Retrieves at most N items of history for the specified order
      operationId: getHistoryByOrderId
      parameters:
      - name: max
        in: query
        description: Maximum number of history item
        schema:
          type: integer
      - name: order_id
        in: path
        description: ID of order
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderHistory'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Order not found
          content: {}
    put:
      tags:
      - location
      summary: Appends a location
      description: Appends a location to the history for the specified order
      operationId: appendHistory
      parameters:
      - name: order_id
        in: path
        description: ID of order
        required: true
        schema:
          type: string
      requestBody:
        description: Updated Location
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Location'
        required: true
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Order not found
          content: {}
      x-codegen-request-body-name: body
    delete:
      tags:
      - location
      summary: Delete history
      description: Delete history for the specified order.
      operationId: deleteHistory
      parameters:
      - name: order_id
        in: path
        description: ID of order
        required: true
        schema:
          type: string
      responses:
        400:
          description: Invalid order id supplied
          content: {}
        404:
          description: Order not found
          content: {}
components:
  schemas:
    Location:
      type: object
      properties:
        lat:
          multipleOf: 0.01
          type: number
        lng:
          multipleOf: 0.01
          type: number
      xml:
        name: Location
    OrderHistory:
      type: object
      properties:
        order_id:
          type: string
        history:
          type: array
          xml:
            name: OrderHistory
            wrapped: false
          items:
            $ref: '#/components/schemas/Location'